direction: right
me: "me" {shape: image; icon: https://icons.terrastruct.com/essentials%2F365-user.svg}
write: "write" {icon: https://icons.terrastruct.com/essentials%2F112-pen.svg}
push: "git push" {icon: https://icons.terrastruct.com/dev%2Fgit.svg}
live: "ohm.quest" {shape: cloud; icon: https://icons.terrastruct.com/essentials%2F140-internet.svg}
me -> write -> push -> live
